name: Automatic Github Action Commenter
on: pull_request

jobs:
  example_comment_pr:
    if: true
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  example_comment_pr2:
    if: false
    runs-on: ubuntu-latest
    name: An example job to comment a PR2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
