name: Automatic Github Action Commenter

# Controls when the workflow will run
on: pull_request

jobs:
  example_comment_pr:
    if: $(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l) > 0
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world!!!
            ${{ count -gt 0 }}
          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
