name: Assets Check

on: [pull_request]

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Analyze assets size
      run: `find assets/ -type f -size +100k -exec ls -lh {} \; | awk '{ print $9 "|| Size : " $5 }'`
