name: Assets Checker

# Controls when the workflow will run
#                github.issues.createComment({
#                   body: '👋 Thanks for reporting! You have many assets > 100kb'
#                 })
#   github.issues.createComment({
#                   body: '👋 Thanks for reporting! All assets are less than 100 kb'
#                 })
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
#           message: |
#             Hello world ! :wave: ${{count}}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            echo "counting"
            count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
            echo $count
             if [ "$count" -gt 0 ]; then
                echo "yes"
            else
                echo "no"
            fi
 
      - uses: actions/checkout@v3
      - name: Run asset test
        run: |
          count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
          if [ "$count" -gt 0 ]; then
            exit 1
          else
            exit 0
          fi
          

