name: Assets Checker
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      - name: Set Asset count in Env. Variable
        run: |
          count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
          echo "assets_count=${count}" >> $GITHUB_ENV
 
      - name: Comment PR for invalid assets
        if: ${{env.assets_count != 0}}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Oops :eyes: :eyes: !!! You have assets with size more than 100Kb. Please optimize them. 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR for valid assets
        if: ${{env.assets_count != 0}}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Woohooo :rocket: !!! Congratulations, your all assets are less than 100Kb. 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/checkout@v3
      - name: Run asset test
        run: |
          count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
          if [ "$count" -gt 0 ]; then
            echo "action_state=${count}" >> $GITHUB_ENV
            exit 1
          else
            exit 0
          fi
          

