name: Assets Checker
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set the count value
        id: step_one
        run: | 
          count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
          echo "$count"
      - name: use the value
        id: step_two
        run: |
          echo "${evn}"
          echo "${env.count}"
    
      - name: Comment PR
        if: true
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR
        if: false
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - uses: actions/checkout@v3
      - name: Run asset test
        run: |
          count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
          if [ "$count" -gt 0 ]; then
            exit 1
          else
            exit 0
          fi
          

