name: Assets Checker

# Controls when the workflow will run
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run asset test
        run: |
          count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
          if [ "$count" -gt 0 ]; then
            exit 1
          else
            exit 0
          fi
          
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
#           message: |
#             Hello world ! :wave: ${{count}}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
             if [ "$count" -gt 0 ]; then
               github.issues.createComment({
                  body: '👋 Thanks for reporting! You have many assets > 100kb'
                })
            else
              github.issues.createComment({
                  body: '👋 Thanks for reporting! All assets are less than 100 kb'
                })
            fi
           

