name: Assets Checker
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      - name: Set asset count
        run: |
          count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
          echo "count=${count}" >> $GITHUB_ENV
          if [ "$count" -gt 0 ]; then
             echo "has_invalid_size_assets=true" >> $GITHUB_ENV
           else
             echo "has_invalid_size_assets=false" >> $GITHUB_ENV
           fi
 
      - name: Comment PR
        if: ${{env.count > 0}}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave - 1st 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR
        if: ${{env.count > 10}}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave - 1st 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Comment PR
        if: ${{env.has_invalid_size_assets}}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave - 2nd:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: use the value
        id: step_two
        run: |
          echo "${{env.count}}"
          echo "${{env.action_state}}"
          echo "${{env.action_state2}}"


#       - uses: actions/checkout@v3
#       - name: Run asset test
#         run: |
#           count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
#           if [ "$count" -gt 0 ]; then
#             echo "action_state=${count}" >> $GITHUB_ENV
#             exit 1
#           else
#             exit 0
#           fi
          

