name: Assets Checker

# Controls when the workflow will run
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run asset test
        run: |
          count=$(find assets/ -type f -size +100k -exec ls -lh {} \; | wc -l)
          if [ "$count" -gt 0 ]; then
            exit 1
          else
            exit 0
          fi
          
      - name: Comment PR
        if: $count -gt 0
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave: $count
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

